### ISSUE TITLE
Define Wishlist Item Model

### ISSUE THREAD

**Issue by jay-goettelmann-nyu** [CSCI-GA-2820-FA23-003/wishlists#19]
**As a** Customer
**I need** a wishlist item defined
**So that** I can see basic information for an item I would like to review/purchase in the future
   
 ### Details and Assumptions
 * Our API code has a connection to a postgreSQL relational database 
 
* Schema details:
* Primary Key - wishlist_item_id
* Foreign Key - wishlist_id
* Product ID - product_id
* Product Name - product_name
* Product Image URL - product_image_url
* Product Size - product_size
* Product Color - product_color
* Timestamp Added to List - time_added
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a wishlist item exists in the database table
 When I instantiate an instance of the model based on this item id
 Then the model object attributes match values from the database table.
```

**Comment by jay-goettelmann-nyu** [comment]
Per our Planning discussion we will go with the simpler one-to-many approach where wishlist_id will be a foreign key on the wishlist_items table.  We will live with the potential data duplication.

**Comment by studentgrad0419** [comment]
I think for this sprint, we may not need many attributes for a wishlist item to meet our acceptance criteria. 
wishlist_item_id, wishlist_id, product_id, product_name, and product_price should be sufficient.
