### ISSUE TITLE
Update a Wishlist

### ISSUE THREAD

**Issue by rahilkadakia** [CSCI-GA-2820-FA23-003/wishlists#21]
**As a** User
**I need** to update a wishlist
**So that** I can make changes to my existing wishlist
   
 ### Details and Assumptions
 * A wishlist already exists in the database, linked with the user's primary key.
 * Each wishlist has a unique key identifier.
 * Endpoint: PUT /wishlists/{wishlist_id}
 * Input data is a JSON format
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I have already created a wishlist
 When I send a request to change the details of the wishlist
 Then I receive a success code and receive a response which includes the updated data
```

**Comment by studentgrad0419** [comment]
I think updating a wishlist involves updating an attribute like the name of the wishlist. That could be specified as part of the acceptance criteria.

e.g. Given wishlist exists, When I send a request to update with a new name in specifying a re-name, then the wishlist updates with the new information.
