### ISSUE TITLE
List wishlists

### ISSUE THREAD

**Issue by raymondlu8547** [CSCI-GA-2820-FA23-003/wishlists#23]
As a Customer
I need to see all my wishlists
So that I decide which of them need to be changed

**Details and Assumptions**
There exists a model for wishlists
There exists a database to request wishlist information

**Acceptance Criteria**
Given I am a customer
When I send a list request for my wishlists
Then I receive a list of all my wishlists

**Comment by jay-goettelmann-nyu** [comment]
Duplicate of #7
