### ISSUE TITLE
Update a wishlist item

### ISSUE THREAD

**Issue by Dracco30** [CSCI-GA-2820-FA23-003/wishlists#6]
**As a** Customer
**I need to** have the ability to change the quantity of items on my wishlist
**So that** I can maintain a desired quantity for later purchase
   
 ### Details and Assumptions
 * Quantity is really the only attribute that would need updating with a PUT statement.  Attributes like color, size, etc should not change (Although we discussed a different persona having potential requirements e.g. Product Manager updates the Color from blue to sapphire.
 * Endpoint: PUT /wishlists/{wishlist_id}/items/{wishlist_item_id}
 *  Input data is a JSON format
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a user specifies a valid wishlist item and provides an updated quantity
 When they view the wishlist item
 Then the quantity will have updated to the quantity specified
```

**Comment by studentgrad0419** [comment]
Note, this might work like updating an amount for an item
