### ISSUE TITLE
Create Publish Wishlist Action Endpoint

### ISSUE THREAD

**Issue by yDu98** [CSCI-GA-2820-FA23-003/wishlists#62]
**As a** Customer
**I need to** have a mechanism for making my wishlist publicly viewable
**So that** I can influence my followers and give my family great ideas for holiday gifts.

**Details and Assumptions**
- Wishlists will be private by default
- A new attribute exists (is_public) which defaults to false
- Form: /wishlists/{wishlist_id}/publish

**Acceptance Criteria**
```gherkin
Given a private wishlist
When I call the /publish endpoint
Then the is_public value returned will be true
```

**Comment by studentgrad0419** [comment]
Hi Yanfeng, I think an action could be applicable to both a "wishlist" like "lock/unlock/make a copy?"
and "wishlist items" to "lock/unlock/make copy " as well. So this might be split into 2 different stories.
