### ISSUE TITLE
Create a Wishlist List

### ISSUE THREAD

**Issue by Dracco30** [CSCI-GA-2820-FA23-003/wishlists#7]
**As a** Wishlist Admin
**I need to** View all of wishlists that exist in the system
**So that** I can organize and access the different collections of products created by customers
   
 ### Details and Assumptions
 * The system may have have zero or more (unlimited) wishlists
 * Endpoint form: GET /wishlists
 
 ### Acceptance Criteria  
   
 ```gherkin
 Given a user with access to the system
 When a request is made to list all wishlists
 Then the endpoint should return a list of wishlist object details.  This list count should match the number of wishlists stored in the database.
```

 ```gherkin
 Given a user with access to the system and an empty wishlists table
 When a request is made to list all wishlists
 Then the endpoint should return an empty collection with a 200 status
```

**Comment by studentgrad0419** [comment]
I think "Create a WishList List" might be a better title

**Comment by studentgrad0419** [comment]
I think it might be better to re-word as "Create a Wishlist List".
Also apologies for closing before, I am still new to the UI.

**Comment by jay-goettelmann-nyu** [comment]
Updated the Name of this.  We may want to touch up a bit of this one.  It's itended to show all the lists that a customer owns correct?  e.g. My Christmas List, My Birthday List, My Wedding Registry
